name: Deploy to cPanel via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: ./
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.cpanel.yml
            **/.ftp-deploy-sync-state.json
            **/README*
            **/node_modules/**
